#!/bin/bash

# init.d script with help from:
# http://ubuntuforums.org/showthread.php?t=1704166

PROG="tor"
PROG_PATH="/usr/local/bin"
PID_PATH="/var/run"
LOG_PATH="/var/log"

start() {
  if [ -e "$PID_PATH/$PROG.pid" ]; then
    echo "Error! $PROG is currently running" 1>&2
    exit 1
  else
    $PROG_PATH/$PROG 2>&1 >$LOG_PATH/$PROG &
    echo "$PROG started"
    touch "$PID_PATH/$PROG.pid"
  fi
}

stop() {
  if [ -e "$PID_PATH/$PROG.pid" ]; then
    killall $PROG
    rm $PID_PATH/$PROG.pid
    echo "$PROG stopped"
  else
    echo "Error! $PROG not running" 1>&2
    exit 1
  fi
}

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

case "$1" in
  start)
    start
    exit 0
  ;;
  stop)
    stop
    exit 0
  ;;
  reload|restart|force-reload)
    stop
    start
    exit 0
  ;;
  **)
    echo "Usage: $0 {start|stop|reload}" 1>&2
    exit 1
  ;;
esac
